[package]

name = "piston2d-opengl_graphics"
version = "0.60.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>"
]
keywords = ["opengl", "graphics", "2d", "piston"]
description = "An OpenGL 2D back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/opengl_graphics.git"
homepage = "https://github.com/PistonDevelopers/opengl_graphics"
documentation = "https://docs.rs/piston2d-opengl_graphics"

[lib]
name = "opengl_graphics"
path = "src/lib.rs"

[dependencies]
image = "0.21.0"
gl = "0.11.0"
piston-shaders_graphics2d = "0.3.1"
piston-texture = "0.6.0"
piston-viewport = "0.5.0"
shader_version = "0.3.0"
fnv = "1.0.2"

[dependencies.piston2d-graphics]
version = "0.30.0"
features = ["glyph_cache_rusttype"]

[dev-dependencies]
piston = "0.40.0"
pistoncore-sdl2_window = "0.53.0"
rand = "0.6.0"

[build-dependencies]
khronos_api = "2.1.0"
